<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.Tools">
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Grpc.Core.Api" />
      <PackageReference Include="Google.Protobuf" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="files.proto">
        <GrpcServices>Both</GrpcServices>
        <Access>Public</Access>
        <ProtoCompile>True</ProtoCompile>
        <CompileOutputs>True</CompileOutputs>
        <OutputDir>obj\Debug\net10.0\</OutputDir>
        <Generator>MSBuild:Compile</Generator>
      </Protobuf>
    </ItemGroup>

</Project>
